config/routes.rb
Rails.application.routes.draw do
  resources :sharings
  devise_for :users,
  :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'}
    devise_scope :user do
      get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
      get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sharings#index"
  match '/:id', :controller => 'profiles', :action => 'show', :as => 'profile', :via => :get
end

app/models/sharing.rb
class Sharing < ApplicationRecord
  belongs_to :user
  validates_length_of :content, :minimum => 5
end

app/controllers/sharings_controller.rb
class SharingsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :new]

  def index
    @sharings = Sharing.all
    @sharing = Sharing.new
  end

  def show
    @sharing = Sharing.find(params[:id])
  end

  def new
    @sharing = Sharing.new
  end

  def create
    @sharing = current_user.sharings.build(params[:sharing])

    if @sharing.save
      if current_user
        current_user.tweet!(@sharing.content) if current_user.connected_to?(:twitter)
        current_user.fb_post!(@sharing.content) if current_user.connected_to?(:facebook)
      end

      redirect_to(:action => "index", :notice => 'Sharing was successfully created.')
    else
      @sharings = Sharing.all
      render :action => "new"
    end
  end
end

app/helpers/sharings_helper.rb
module SharingsHelper
end

app/views/sharings/_form.html.erb
<%= simple_form_for(@sharing) do |f| %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/sharings/index.html.erb
<h1>Share something to your networks</h1>

<% if !current_user.nil? %>
    <div class="sharing_form">
      <h2>Post to connected networks!</h2>
      <%= render 'sharings/form' %>
    </div>
<% else %>
    <div class="sharing_signup_call_to_action">
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "sign in", new_user_session_path %> to share.

    </div>
<% end %>

<h2>Hello!</h2>

<% if @sharings.empty? %>
  <P>Lets share something</P>
<% end %>

<% @sharings.each do |sharing| %>
    <div class="sharing" style="clear:both;">
      <%= link_to image_tag(sharing.user.photo.url(:mini), :class => 'share_image'), profile_path(sharing.user) %>
      <div class="share_text">
        <%= sharing.content %>
        <br/>
        <br/>
        <%= sharing.created_at.strftime("%m/%d/%Y %I:%M%p GMT") %> | <%= link_to "permalink", sharing_path(sharing) %> |

        <a href="http://twitter.com/share"
           class="twitter-share-button"
           data-url="<%= sharing_url(sharing) %>"
           data-text="<%= sharing.content %>"
           data-count="horizontal">Tweet</a>


        <fb:like href="<%= sharing_url(sharing) %>"
                 ref="unique_tracking_code_per_referrer_goes_here"
                 layout="button_count"
                 show_faces="false"
                 width="10"
                 action="like"
                 font="verdana">
        </fb:like>

      </div>
    </div>

<% end %>

app/views/sharings/new.html.erb
<h1>Share something to your networks</h1>

<div class="sharing_form">
  <h2>Post to connected networks!</h2>
  <%= render 'sharings/form' %>
</div>

app/views/sharings/show.html.erb
<% content_for :page_specific_head do %>
    <meta property="og:title" content="The Lean Startup Book"/>
    <meta property="og:site_name"   content="<%= DEFAULT_FB_POST_NAME %>"/>
    <meta property="og:description" content="<%= @sharing.content %>"/>
    <meta property="og:image"       content="<%= DEFAULT_FB_SHARE_IMAGE %>"/>
    <meta property="og:url"         content="<%= request.url %>"/>
    <meta property="fb:admins"      content="100001665281750"/>
    <meta property="og:type"        content="website"/>
<% end %>

<h1><%= @sharing.user.display_name %> shared this</h1>

<div class="sharing" style="clear:both;">
  <%= link_to image_tag(@sharing.user.photo.url(:mini), :class => 'share_image'), profile_path(@sharing.user) %>
  <div class="share_text">
    <%= @sharing.content %>
    <br/>
    <br/>
    <%= @sharing.created_at.strftime("%m/%d/%Y %I:%M%p GMT") %> | <%= link_to "permalink", sharing_path(@sharing) %> |

    <a href="http://twitter.com/share"
       class="twitter-share-button"
       data-url="<%= sharing_url(@sharing) %>"
       data-text="<%= @sharing.content %>"
    data-count="horizontal">Tweet</a>

    <fb:like href="<%= sharing_url(@sharing) %>"
             ref="unique_tracking_code_per_referrer_goes_here"
             layout="button_count"
             show_faces="false"
             width="10"
             action="like"
             font="verdana">
    </fb:like>


  </div>
</div>

<%= link_to "Share something yourself", new_sharing_path %>