config/routes.rb
Rails.application.routes.draw do
  resources :sharings
  devise_for :users,
  :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'}
    devise_scope :user do
      get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
      get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sharings#index"
  match '/:id', :controller => 'profiles', :action => 'show', :as => 'profile', :via => :get
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsNV</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 'forms', 'reset', 'scaffold', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta property="title" content="<%= @page_title || ENV["DEFAULT_PAGE_TITLE"] %>"/>

    <meta property="description" content="<%= @page_description || ENV["DEFAULT_PAGE_DESCRIPTION"] %>"/>
    <%= content_for :page_specific_head %>
  </head>

  <!-- Navigation -->
  <body>

    <div class="page_content">
      <div id="user_nav" class="row">
        <div class="left-part">
          <%- if controller_name != 'sessions' %>
            <%= link_to "Log in", new_session_path(resource_name) %><br />
          <% end -%>

          <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
            <%= link_to "Sign up", new_registration_path(resource_name) %><br />
          <% end -%>

          <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
          <% end -%>

          <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
            <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
          <% end -%>

          <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
            <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
          <% end -%>
        </div>
        <div class="right-part">
          <%= link_to 'Home', '/' %>
  	      <% if user_signed_in? %>
  	        Signed in as <%= current_user.email %>. Not you?
            <%= link_to 'Profile', profile_path(current_user) %>
            <%= link_to 'Edit Profile', edit_user_registration_path(current_user) %>
  	        <%= link_to "Sign out", destroy_user_session_path %>
  	      <% else %>
  	        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  	      <% end %>
        </div>


      </div>
      <%= render 'devise/shared/links' %>
      <div style="height: 10px">
        <%= render 'devise/shared/alerts' %>
      </div>


      <%= yield %>
	  </div>





    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

    <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
  </body>
</html>